--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (165f042)
-- Dumped by pg_dump version 16.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: leads; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.leads (
    id integer NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    phone character varying(20) NOT NULL,
    email text NOT NULL,
    license_goal text NOT NULL,
    source text DEFAULT 'voice_agent'::text NOT NULL,
    status text DEFAULT 'new'::text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    pain_points text,
    employment_status character varying(100),
    urgency_level character varying(50),
    payment_preference character varying(50),
    payment_status character varying(20) DEFAULT 'NOT_PAID'::character varying,
    confirmation_number character varying(100),
    agent_name character varying(100),
    supervisor character varying(100) DEFAULT 'Kelli Kirk'::character varying,
    lead_source character varying(100),
    call_summary text,
    call_date timestamp without time zone,
    conversation_id character varying(100),
    unanswered_call_attempts integer DEFAULT 0,
    last_call_attempt_at timestamp without time zone
);


ALTER TABLE public.leads OWNER TO neondb_owner;

--
-- Name: leads_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.leads_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.leads_id_seq OWNER TO neondb_owner;

--
-- Name: leads_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.leads_id_seq OWNED BY public.leads.id;


--
-- Name: leads id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.leads ALTER COLUMN id SET DEFAULT nextval('public.leads_id_seq'::regclass);


--
-- Data for Name: leads; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (1, 'Gerard', 'LeBron', '978-818-5990', 'yeraldlebron@gmail.com', '2-15', 'voice_call', 'enrolled', '2025-08-06 17:00:31.212974', '2025-08-06 17:00:31.212974', 'Needs start date and class schedule information', 'Seeking career change', 'High', NULL, 'NOT_PAID', NULL, 'Jennifer', 'Kelli Kirk', 'Phone Call to Main Number', 'Existing 2-15 student calling for class start date. Already enrolled but needs schedule details and login access. Agent Jennifer handled call, confirmed contact info, explained class schedule (Mon/Tue/Thu/Fri 9AM-1PM, Web Wednesday coaching).', '2025-08-06 17:00:00', NULL, 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (2, 'Jason', '', '4407-401-3100', 'ipowermovespodcast@gmail.com', '2-15', 'voice_call', 'qualified', '2025-08-06 17:04:01.816676', '2025-08-06 17:04:01.816676', 'Wants comprehensive licensing for maximum career opportunities and income streams', 'Entrepreneur (podcast owner)', 'High', '$199 down payment with financing options', 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'Phone Call to Main Number', 'New Florida prospect interested in 2-15 license. Asked multiple qualifying questions, showed strong buying signals, requested enrollment immediately. Agent Mandy explained $479 total cost with $199 down payment option. Provided financing options (Klarna, Afterpay, Affirm). Sent enrollment links to both phone and email. High conversion probability.', '2025-08-06 17:03:00', 'call_jason_mandy_080625', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (5, 'OS', 'Ahmed', '', '', 'Continuing Education', 'voice_call', 'CE_inquiry', '2025-08-06 17:10:23.998597', '2025-08-06 17:10:23.998597', 'Requested direct access to Kelli for continuing education inquiry. Agent initially misunderstood need and tried to sell 2-15 new licensing course. Had to clarify multiple times that he needed CE, not new licensing.', 'Licensed insurance agent', 'Medium', NULL, 'NOT_PAID', NULL, 'Mandy (+ transfer to CE department)', 'Kelli Kirk', 'Continuing Education Inquiry', 'Licensed agent Ahmed called requesting to speak directly with Kelli about continuing education. Agent Mandy initially tried to sell 2-15 new licensing course despite Ahmed''s clear CE request. When Ahmed clarified ''I need to consider an education'' (continuing education), got transferred. Communication breakdown - agent didn''t listen to actual customer need and pushed wrong service.', '2025-08-06 17:10:00', 'call_ahmed_ce_080625', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (6, 'Johnny', 'Burnett', '', '', 'AHIP/Medicare (not offered)', 'voice_call', 'wrong_inquiry', '2025-08-06 17:16:10.56861', '2025-08-06 17:16:10.56861', 'Seeking AHIP Medicare certification course which company doesn''t offer. Needs education on proper licensing sequence (state pre-licensing first, then AHIP).', 'Unknown', 'Low', NULL, 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'AHIP Inquiry (Misdirected)', 'Johnny Burnett from Jacksonville called asking for AHIP course (Medicare certification). Agent Mandy correctly informed him we don''t offer AHIP and explained we specialize in Florida pre-licensing (2-15, 2-40) which are prerequisites before AHIP. Agent began explaining proper licensing sequence. Potential convert to 2-15 or 2-40 program.', '2025-08-06 17:15:00', 'call_johnny_burnett_ahip_080625', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (8, 'Maria', 'Rodriguez', '954-332-7891', 'maria.rodriguez@gmail.com', '2-15', 'voice_call', 'qualified', '2025-08-07 16:36:31.112258', '2025-08-07 16:36:31.112258', 'Single mom transitioning from retail to insurance. Needs flexible payment plan due to tight budget. Concerned about study time while working full-time at Target.', 'Retail worker (Target)', 'High', 'Payment plan', 'NEEDS_PAYMENT_PLAN', NULL, 'Mandy', 'Kelli Kirk', 'Career Change - Retail to Insurance', 'Maria Rodriguez called interested in 2-15 licensing after seeing job postings. Single mother working at Target, wants career change for better income. Expressed serious interest but concerned about $895 course cost. Agent Mandy explained payment plan options (3-4 monthly payments). Maria appreciated flexible options and wants to start ASAP. Needs to speak with supervisor about scheduling around work shifts.', '2025-08-07 16:30:00', 'call_maria_rodriguez_2-15_080725', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (9, 'Robert', 'Thompson', '813-555-4892', 'rthompson.realtor@outlook.com', '2-40', 'website', 'new', '2025-08-07 16:36:42.839439', '2025-08-07 16:36:42.839439', 'Real estate agent looking to expand into property insurance sales. Needs 2-40 license quickly due to upcoming client opportunity. Frustrated by previous failed online course experience with another provider.', 'Licensed real estate agent', 'Very High', 'Full payment', 'NOT_PAID', NULL, 'Jessica', 'Kelli Kirk', 'Real Estate Agent Expansion', 'Robert Thompson, licensed real estate agent from Tampa, submitted inquiry through website. Has immediate client opportunity requiring property insurance knowledge. Previous bad experience with online course from competitor that was "disorganized and unhelpful." Wants assurance about course quality and instructor availability. Needs to start within 48 hours.', '2025-08-07 14:45:00', 'web_robert_thompson_2-40_080725', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (10, 'Lisa', 'Chen', '305-888-2341', 'lisa.chen.miami@yahoo.com', '2-15', 'referral', 'contacted', '2025-08-07 16:36:55.283883', '2025-08-07 16:36:55.283883', 'Banking professional looking for side income. Husband also interested in insurance career. Needs evening/weekend course schedule due to full-time bank job. Concerned about exam difficulty.', 'Bank loan officer', 'Medium', 'Full payment', 'NOT_PAID', NULL, 'Michael', 'Kelli Kirk', 'Banking Professional - Side Income', 'Lisa Chen referred by previous student (her sister-in-law). Works as loan officer at Wells Fargo, wants insurance license for additional income streams. Husband David also considering career change. Both need flexible scheduling around banking hours. Lisa asked detailed questions about pass rates and study materials. Expressed confidence in ability to learn but wants assurance about exam preparation quality.', '2025-08-07 11:20:00', 'call_lisa_chen_referral_080725', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (3, 'Richard', 'Powell', '', '', '2-15', 'voice_call', 'enrolled', '2025-08-06 17:05:21.241879', '2025-08-14 20:10:26.848', 'Instructor Jason missed scheduled 10 AM class today and last night''s session. Student needs direct contact from instructor.', 'Current student', 'CRITICAL', NULL, 'PAID', NULL, 'Mandy', 'Kelli Kirk', 'Existing Student - Service Call', 'Enrolled 2-15 student reporting instructor Jason missed today''s 10 AM class and last night''s session. Student frustrated and requesting callback from Jason. Agent provided office contact info (407-332-6645) and email (kelli@cflis.com). URGENT FOLLOW-UP REQUIRED.', '2025-08-06 17:05:00', 'call_richard_powell_080625', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (4, 'Veronica', '', '', '', 'Continuing Education', 'voice_call', 'qualified', '2025-08-06 17:08:10.435395', '2025-08-14 20:10:44.746', 'CUSTOMER SERVICE DISASTER - Customer repeatedly demanded to ''talk to a real person'' indicating agents sounded like AI/bots. Simple CE inquiry became frustrating transfer nightmare.', 'Licensed insurance agent', 'CRITICAL', NULL, 'NOT_PAID', NULL, 'Multiple Transfer Failure (Mandy, Jennifer)', 'Kelli Kirk', 'Continuing Education Inquiry', 'MAJOR SERVICE FAILURE: Licensed agent Veronica called for continuing education course info. Got bounced between 3 agents (Mandy→Jennifer→Mandy). Customer repeatedly said ''I need to talk to a real person'' and ''I need to talk to an agent please'' - clear indication she thought she was speaking to automated/AI systems. Became increasingly frustrated with each transfer. Hung up saying ''No, absolutely not'' and refused all assistance. CRITICAL ISSUE: Agents either sound robotic or customer detected AI system.', '2025-08-06 17:07:00', 'call_veronica_service_failure_080625', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (12, 'María', 'Álvarez', '', '', '2-20', 'voice_agent', 'new', '2025-08-08 16:17:01.871441', '2025-08-08 16:17:01.871441', NULL, NULL, NULL, NULL, 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', NULL, 'Spanish-speaking prospect María Álvarez called asking about 2-20 (commercial insurance) license requirements. Call appears to have just started when transcript cuts off.', NULL, NULL, 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (11, 'Ashley', '', '', '', 'TBD - Inquiring about options', 'voice_call', 'new', '2025-08-07 16:39:03.397824', '2025-08-07 16:39:03.397824', 'Exploring insurance licensing career options. Needs information about class structure and license types.', 'Unknown', 'Medium', '', 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'Class Information Inquiry', 'Multiple unanswered calls - prospect requesting information about classes and Jason', '2025-08-07 16:45:00', 'call_ashley_class_inquiry_080625', 3, '2025-08-08 16:27:14.581846');
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (16, 'Samantha', 'MISSING_REQUIRED', 'MISSING_REQUIRED', 'MISSING_REQUIRED', 'Health insurance (2-40 or 2-15 pending)', 'voice_agent', 'hot_lead', '2025-08-08 17:28:23.717682', '2025-08-08 17:28:23.717682', 'Ready to start career as health insurance agent', NULL, 'high', NULL, 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', NULL, 'Strong prospect Samantha expressed clear interest in health insurance license. Has ''always wanted to be a health insurance agent'' and ready to start immediately. Was being transferred to Jennifer in Admissions but system experienced technical loop failure. HOT LEAD - REQUIRES IMMEDIATE CALLBACK.', '2025-08-08 17:28:23.717682', 'conv_1201k25awbzjf9wax7w9mbm74y8r', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (18, 'Not provided', 'MISSING_REQUIRED', '+17723217238', 'MISSING_REQUIRED', 'AHIP', 'voice_agent', 'returning_customer', '2025-08-13 17:05:33.614118', '2025-08-13 17:05:33.614118', 'Needs early AHIP certification renewal. Specifically requested Kelli Kirk based on previous positive experience.', NULL, 'medium', NULL, 'NOT_PAID', NULL, 'Sarah Patterson', 'Kelli Kirk', 'Inbound call - returning customer', 'Returning customer contacted The-Insurance-School.com seeking early AHIP renewal. After initial transfers, connected with Sarah Patterson at Florida Insurance School Industry Resource Network. Customer specifically requested Kelli Kirk based on prior experience. Sarah confirmed Kelli will follow up within 1-2 days.', NULL, 'conv_2001k2fez3aqfqm8c6gw5cz5xtyd', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (19, 'Connie', '(CE)', '+18638753740', '', 'CE', 'voice_agent', 'enrolled', '2025-08-13 17:08:27.396763', '2025-08-14 20:09:55.824', 'Unsure of CE requirements. Needs custom CE plan created.', NULL, 'low', NULL, 'NOT_PAID', 'AOO9113', 'Sarah', 'Kelli Kirk', 'Inbound call - CE inquiry', 'Connie called about continuing education credits. After initial misdirection, transferred to Sarah in CE division. Connie unsure of CE requirements. Sarah arranged for Kelli Kirk to create custom CE plan. License number AOO9113 confirmed. Kelli to contact within 24-48 hours.', NULL, 'conv_5701k2fdxw7zf4y8tpsc482f210y', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (7, 'John', 'Fiacabo', '321-594-0454', '', '2-15', 'voice_call', 'enrolled', '2025-08-06 17:17:24.186827', '2025-08-14 20:10:12.322', 'CE due August 2025 (this month). Long-time customer wants personal service from Kelli who knows him personally. Doesn''t want standard process.', 'Licensed agent (71 years old)', 'High', NULL, 'HISTORICAL_CUSTOMER', NULL, 'Mandy + CE Specialist', 'Kelli Kirk', 'CE Renewal - Long-term Customer', 'Long-time loyal customer John Fiacabo called for CE renewal due in August. Has been with company ''many many years.'' Provided phone 321-594-0454. Holds 2-15 license, needs 20 CE hours total (4 hours Law/Ethics + 16 elective). Agent went through standard intake but customer repeatedly requested Kelli call him back personally since ''she knows me.'' Established customer relationship with Kelli.', '2025-08-06 17:17:00', 'call_john_fiacabo_ce_080625', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (20, 'MISSING_REQUIRED', 'MISSING_REQUIRED', '+15617442086', 'MISSING_REQUIRED', 'CE', 'voice_agent', 'new', '2025-08-18 19:13:58.08299', '2025-08-18 19:13:58.08299', 'CE credits', NULL, NULL, NULL, 'NOT_PAID', NULL, 'CE resource specialist', 'Kelli Kirk', NULL, 'The user called The Insurance School looking for Kelly. The call was initially routed to a CE resource specialist, but the user repeatedly requested Kelly. The agent clarified the user was looking for Kelli Kirk and offered to transfer them back to the main line. After a few attempts to connect the user was able to leave a message for Kelli with their name, number, and reason for calling (CE credits).', NULL, 'conv_8401k2q114gwf2r8650mktegy3rc', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (21, 'Sharon', 'Haag', '+19418071542', 'MISSING_REQUIRED', 'Health and Life CE', 'voice_agent', 'new', '2025-08-18 19:15:25.781306', '2025-08-18 19:15:25.781306', 'Unsure of exact CE hour requirements, prefers online courses', NULL, 'medium', NULL, 'NOT_PAID', NULL, 'Sarah Patterson', 'Kelli Kirk', 'Florida Insurance Industry Resource Network', 'The user, Sharon Haag, contacted the Florida Insurance Industry Resource Network to inquire about CE credits for her Health and Life license, which is due for renewal in October. She prefers online courses and is unsure of her exact CE hour requirements. The agent, Sarah Patterson, gathered Sharon''s information and will have Kelli Kirk, a Senior Coordinator, contact Sharon within 48 hours with a customized education plan.', '2025-08-18 19:15:25.781306', 'conv_2401k2pxsa4bezqvhjmq0y7770h2', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (22, 'Regina', 'Dietrich', '+17723217238', 'MISSING_REQUIRED', 'AHIP renewal', 'voice_agent', 'new', '2025-08-18 19:17:23.880848', '2025-08-18 19:17:23.880848', 'No callback received after 2 days, needs urgent AHIP renewal assistance', NULL, 'high', NULL, 'NOT_PAID', NULL, 'Sarah', 'Kelli Kirk', NULL, 'The user, Regina Dietrich, called to speak with Kelly regarding her AHIP renewal, but had not received a call back after a previous attempt two days prior. The agent, Sarah, apologized for the delay and escalated the issue to Kelly as an urgent matter.', NULL, NULL, 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (23, 'Zaymara', 'Olano', '+17862389663', 'MISSING_REQUIRED', '2-14', 'voice_agent', 'new', '2025-08-21 15:21:39.641801', '2025-08-21 15:21:39.641801', 'IMPORTANT: Zaymara Olano (former student) called to enroll HER SON - prospect name may need correction. Multiple failed transfer attempts to Admissions department (Jennifer) - system kept looping back to initial agent.', NULL, 'high', NULL, 'NOT_PAID', NULL, 'MISSING_REQUIRED', 'Kelli Kirk', NULL, 'Zaymara Olano called to enroll her son in 2-14 Life Insurance course. Son confirmed ready to start immediately. Agent attempted multiple transfers to Jennifer in Admissions but system malfunctioned, looping calls back. Transfer issue unresolved. NOTE: Lead name shows mother''s name, not son''s.', NULL, 'conv_6201k34hk5ssf5jvq7vd6fmgkqfp', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (24, 'MISSING_REQUIRED', 'MISSING_REQUIRED', '+13219006039', 'MISSING_REQUIRED', 'CE Requirements', 'voice_agent', 'new', '2025-08-21 15:25:21.349791', '2025-08-21 15:25:21.349791', 'Caller asked for Kelly (possibly Kelli Kirk). Multiple transfers: first to Continued Education Resource Department, then back to main line, finally to Sarah Patterson at Florida Insurance School Industry Resource Network, Continued Education Division.', NULL, 'medium', NULL, 'NOT_PAID', NULL, 'MISSING_REQUIRED', 'Kelli Kirk', NULL, 'Caller inquired about CE requirements and requested Kelly. Transferred multiple times before reaching Sarah Patterson who offered assistance with CE requirements. No personal information collected.', NULL, 'conv_4901k33ypm39fggr9e4n7dvfesz8', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (25, 'Irene', 'MISSING_REQUIRED', '+14079891997', 'MISSING_REQUIRED', 'MISSING_REQUIRED', 'voice_agent', 'new', '2025-08-21 15:26:56.491727', '2025-08-21 15:26:56.491727', 'Customer felt like she was talking to a robot. Needs clarification on: 90-day access details, costs for reviews, retake policy. Currently comparing with competitor offerings. Requires personal touch from lead instructor.', NULL, 'high', NULL, 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'Inbound call - shopping/comparing', 'Irene called seeking detailed information about live course program. Expressed frustration about robotic interaction. Has specific questions about 90-day access, review costs, and retake policy compared to competitors. Mandy assigned follow-up to Jason Perez (lead instructor) for callback to 407-989-1997.', NULL, 'conv_8901k31s07gjfkj9z9pa4z0vzqk9', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (27, 'PLACEHOLDER', 'PLACEHOLDER', '+1 689 221 4151', 'placeholder@email.com', '2-15', 'voice_agent', 'new', '2025-09-05 19:40:13.259502', '2025-09-05 19:40:13.259502', 'Inquiring about course costs, responses were unclear when asked about specific license type', 'PLACEHOLDER', 'PLACEHOLDER', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'The-Insurance-School.com inquiry', 'User asked about course costs, agent provided 2-15 Health and Life pricing ($479) with payment options, tried to clarify if user wanted 2-15 or more specific license but got unclear responses', NULL, 'conv_7701k4d8wmh7endbn1b8f9mhq8dh', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (26, 'Grace', 'Coradine', '+1 407 435 0534', 'placeholder@email.com', '2-40', 'voice_agent', 'new', '2025-09-05 19:39:27.505953', '2025-09-05 19:39:27.505953', 'Looking to get 2-40 Health Insurance license', 'Healthcare background', 'PLACEHOLDER', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'The-Insurance-School.com', 'Grace Coradine called about 2-40 Health Insurance license, has healthcare background, scheduled for callback from Jason Perez at 407-435-0534, available anytime', NULL, 'conv_9201k4b7c3t8e5p9bp5n3zqwtbkg', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (29, 'PLACEHOLDER', 'PLACEHOLDER', '+18133240420', 'placeholder@email.com', '2-15', 'voice_agent', 'new', '2025-09-05 19:43:24.692353', '2025-09-05 19:43:24.692353', 'Looking for license to sell benefits', 'PLACEHOLDER', 'low', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'PLACEHOLDER', 'Prospect called The Insurance School asking for operator/representative. Agent Mandy assisted with Florida insurance licensing programs. User interested in license to sell benefits. Agent recommended 2-15 license. User abruptly ended call.', NULL, 'conv_3201k4as39z7eyabfsz7gnrg9n23', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (28, 'George', 'PLACEHOLDER', '+19548150183', 'placeholder@email.com', 'CE_hours', 'voice_agent', 'new', '2025-09-05 19:42:46.391188', '2025-09-05 19:42:46.391188', 'Needs 4 CE hours by December 31, 2025', 'licensed_active', 'high', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Sarah', 'Kelli Kirk', 'PLACEHOLDER', 'George called The Insurance School for CE hours. Transferred to Sarah at Industry Resource Network. Needs 4 more CE hours by December 31, 2025. Prefers online courses, no specific topic preference. Agent gathering information to find suitable courses.', NULL, 'conv_9201k4ae03taf4yvw6sngb2wx5gq', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (30, 'Michelle', 'Rollock', '+17174586363', 'placeholder@email.com', 'CE_hours', 'voice_agent', 'new', '2025-09-05 19:45:51.101966', '2025-09-05 19:45:51.101966', 'Needs 8 CE credits (4 law & ethics, 4 elective) for workers comp claims adjuster', 'licensed_active', 'medium', 'web-based', 'NOT_PAID', NULL, 'Not specified', 'Kelli Kirk', 'PLACEHOLDER', 'Michelle Rollock contacted Insurance School seeking CEU courses for workers'' comp claims adjuster. Transferred to Continued Education Division. Needs 8 credits (4 law & ethics, 4 elective) via web-based, self-paced courses. Deadline September 2025. Agent collected contact info. Kelli Kirk to follow up within 48 hours with customized education plan.', NULL, 'conv_0501k48ebhw7egvaybdmmhcqbw0m', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (31, 'Yadielin', '[REQUIRED - NOT PROVIDED]', '+18134669899', '[REQUIRED - NOT PROVIDED]', '2-15', 'voice_agent', 'new', '2025-09-05 19:46:49.626526', '2025-09-05 19:46:49.626526', 'Technical difficulties receiving enrollment link via text and email. Multiple delivery attempts failed.', 'PLACEHOLDER', 'PLACEHOLDER', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Jennifer', 'Kelli Kirk', 'The-Insurance-School-dot-com', 'Prospect called inquiring about insurance courses. Agent Mandy provided information on 2-15 license benefits, then transferred to Jennifer in Admissions. Jennifer explained course details and pricing, attempted multiple times to send enrollment link via text and email but delivery failed. Customer requested to speak with live person, Jennifer offered technical support.', NULL, 'conv_9001k45jd0yne438qm2bvnqw671f', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (32, 'Max', '[REQUIRED - NOT PROVIDED]', '+16463377867', '[REQUIRED - NOT PROVIDED]', 'CE-CREDITS-2-15', 'voice_agent', 'new', '2025-09-05 19:47:43.939822', '2025-09-05 19:47:43.939822', 'Needs 24 CE credit hours for license renewal by September 25th, 2025. Specifically requested to speak with Kelli directly.', 'PLACEHOLDER', 'HIGH', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Sarah', 'Kelli Kirk', 'PLACEHOLDER', 'Prospect called specifically requesting Kelli regarding CE credits. Has existing 2-15 Health and Life license requiring 24 CE hours for renewal by September 25th, 2025. Initial agent transferred to Sarah who collected information. Sarah agreed to pass info to Kelli for callback within 24-48 hours.', NULL, 'conv_2301k45ghebafkz862pj2w82bg61', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (33, 'NEEDS_DATA', 'NEEDS_DATA', '+13216621887', 'NEEDS_DATA', '2-15', 'voice_agent', 'new', '2025-09-15 16:57:22.25758', '2025-09-15 16:57:22.25758', 'PLACEHOLDER', 'PLACEHOLDER', 'PLACEHOLDER', 'PLACEHOLDER', 'NOT_PAID', NULL, 'PLACEHOLDER', 'Kelli Kirk', 'PLACEHOLDER', 'Canadian resident inquired about obtaining a Florida insurance license. Agent confirmed eligibility based on Florida''s requirements and clarified that the school offers the 2-15 license (life, health, and annuity), but not the 2-20 license (property and casualty). The 2-15 course is offered both live online and on-demand for $479, with flexible payment options. The user thanked the agent and ended the call.', NULL, 'conv_0701k4zbrkv2fm0an9rvb5yeh9w3', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (34, 'Mishula', 'NEEDS_DATA', '+19546439290', 'NEEDS_DATA', 'NEEDS_DATA', 'voice_agent', 'new', '2025-09-15 16:58:16.083259', '2025-09-15 16:58:16.083259', 'Wants to enroll in live insurance class', 'PLACEHOLDER', 'high', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Jennifer', 'Kelli Kirk', 'PLACEHOLDER', 'Mandy at The Insurance School initially assists Mishula, who wants to enroll in a live insurance class. Mishula is transferred to Jennifer in Admissions. Jennifer gathers Mishula''s details, encountering some confusion about the spelling of her first name and email. Jennifer sends the enrollment link via email, then via text, and finally offers to enroll Mishula over the phone.', NULL, 'conv_1301k4x6c8wff7m9r15naaqwyqna', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (35, 'NEEDS_DATA', 'NEEDS_DATA', '+18637771366', 'NEEDS_DATA', '2-20', 'voice_agent', 'new', '2025-09-15 16:59:09.92647', '2025-09-15 16:59:09.92647', 'Looking for 440 exam preparation for auto insurance licensing', 'PLACEHOLDER', 'PLACEHOLDER', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Sarah Patterson', 'Kelli Kirk', 'PLACEHOLDER', 'The user called The-Insurance-School-dot-com seeking information on the 440 exam for auto insurance. The agent clarified that the school primarily offers health and life insurance pre-licensing courses (2-15, 2-40, and 2-14 programs) and not the Propert', NULL, 'PLACEHOLDER', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (36, 'Chris', 'LaCepa', '+18137664474', 'NEEDS_DATA', 'CE', 'voice_agent', 'new', '2025-09-15 17:00:20.36922', '2025-09-15 17:00:20.36922', 'Needs continuing education credits', 'PLACEHOLDER', 'PLACEHOLDER', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Sarah Patterson', 'Kelli Kirk', 'repeat_customer', 'Chris LaCepa called The-Insurance-School-dot-com for help with continuing education (CE) credits. The initial agent, Mandy, transferred him to Sarah Patterson at the Resource Department, as the initial line handles new student registration, not CE. Chris confirmed he usually calls to facilitate his CE credits.', NULL, 'conv_0101k4tazab1e6ts5y42s48en3ph', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (37, 'Mark', 'NEEDS_DATA', '+18509824969', 'NEEDS_DATA', '2-15', 'voice_agent', 'new', '2025-09-15 17:01:07.836199', '2025-09-15 17:01:07.836199', 'Needs course schedule that fits with outside sales lifestyle', 'outside sales', 'medium', 'PLACEHOLDER', 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'PLACEHOLDER', 'Mandy from The Insurance School spoke with a user, Mark, about the 2-15 Health and Life insurance course. Mark, who works in outside sales, inquired about the course schedule and how it would fit his lifestyle. Mandy detailed the program''s structure, emphasizing the availability of recorded classes for flexible learning. She then registered Mark for a meet and greet session with Jason Perez to learn more about the program.', NULL, 'conv_3201k4qr8eyzeg8atppxvq5vvmb1', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (38, 'Margaret', 'NEEDS_DATA', '+14074165479', 'NEEDS_DATA', '2-15', 'voice_agent', 'passed_exam', '2025-09-15 17:02:59.460254', '2025-09-15 17:02:59.460254', 'Passing grade not reported to NIPR', 'PLACEHOLDER', 'high', 'PLACEHOLDER', 'PAID', NULL, 'Mandy', 'Kelli Kirk', 'PLACEHOLDER', 'Margaret called The Insurance School because her passing grade for the 2-15 life and health insurance licensing exam wasn''t reported to NIPR. She provided her name, phone number, email, and exam details (date: August 8th, 2025, score: 77). The agent, Mandy, assured her that she would prioritize the issue with Jason and that Margaret should expect a call back that day.', NULL, 'conv_7601k4dp5wgke47821nhk88egnj3', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (45, 'Janet', 'Unknown', '+17869738090', 'janet.unknown.7869738090@placeholder.com', '2-40', 'voice_agent', 'new', '2025-10-16 20:44:34.130389', '2025-10-16 20:44:34.130389', 'Got ping-ponged between agents multiple times - poor handoff process, no pricing information provided during initial contact', NULL, 'high', NULL, 'NOT_PAID', NULL, 'Mandy, Jennifer', 'Kelli Kirk', 'inbound_call', 'Prospect called inquiring about 2-40 health insurance license course enrollment. Initial contact with Mandy, transferred to Jennifer in Admissions for pricing discussion. Phone number collected but prospect was transferred back to main line, then back to Admissions again. Multiple transfers occurred without resolution. Hot lead needs immediate follow-up with concrete pricing and enrollment info.', NULL, 'conv_3501k757stqbeagbdm4bw16nk5yv', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (41, 'MISSING_FIRST_NAME', 'MISSING_LAST_NAME', '445-308-6868', 'missing.drugalcohol@placeholder.com', 'N/A', 'voice_agent', 'disqualified', '2025-09-17 16:02:38.226157', '2025-09-17 16:02:38.226157', 'Looking for drug and alcohol exam information; called wrong business; expressed frustration when told this is outside the school''s expertise', NULL, 'low', NULL, 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'inbound_call', 'The user called The Insurance School seeking information, but was initially unclear about their needs. The agent, Mandy, clarified that the school focuses on Florida insurance licensing courses. The user then requested information on drug and alcohol exams, which the agent explained is outside the school''s area of expertise. The agent offered to end the call so the user could find the appropriate resource. The user expressed frustration.', NULL, 'conv_3401k599t008e5f9vemyhjh5fzas', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (42, 'MISSING_FIRST_NAME', 'MISSING_LAST_NAME', '321-662-1887', 'missing.canadian@placeholder.com', '2-15', 'voice_agent', 'new', '2025-09-17 16:04:41.276099', '2025-09-17 16:04:41.276099', 'Canadian resident seeking Florida insurance license; needs 2-15 license (life, health, and annuity); was informed 2-20 (property and casualty) is not offered', NULL, 'low', NULL, 'NOT_PAID', NULL, NULL, 'Kelli Kirk', 'inbound_call', 'The user, a Canadian resident, inquired about obtaining a Florida insurance license. The agent confirmed eligibility based on Florida''s requirements and clarified that the school offers the 2-15 license (life, health, and annuity), but not the 2-20 license (property and casualty). The 2-15 course is offered both live online and on-demand for $479, with flexible payment options. The user thanked the agent and ended the call.', NULL, 'conv_0701k4zbrkv2fm0an9rvb5yeh9w3', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (43, 'Emilio', 'UNKNOWN_LAST_NAME', '+14078441162', 'emilio.notprovided@placeholder.com', '2-20', 'voice_agent', 'disqualified', '2025-09-23 16:06:53.442353', '2025-09-23 16:06:53.442353', 'Language barrier - initially called in Spanish requesting classes in Spanish. Classes only offered in English. Also wanted 2-20 (property and casualty) license which The Insurance School does not offer - they specialize in 2-15 and 2-40 (health and life insurance). Product mismatch.', NULL, 'low', NULL, 'NOT_PAID', NULL, 'Mandy', 'Kelli Kirk', 'Inbound Call', 'Prospect called inquiring about Spanish classes and 220 license. Agent responded in Spanish, clarified classes are in English only but instructors understand Latino community needs. Prospect clarified wanting 2-20 (property and casualty) license, which The Insurance School does not offer - they specialize in 2-15 and 2-40 (health and life insurance). Dead lead - product mismatch.', NULL, 'conv_9301k5vheh3gezfvrk2j9wrp9krk', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (40, 'Kayla', 'Rivera', '+17863178118', 'kayla.rivera.missing@placeholder.com', '2-15', 'voice_agent', 'existing_customer_issue', '2025-09-17 15:59:12.066808', '2025-09-17 15:59:12.066808', 'PAID customer not receiving login credentials for 2-15 Health and Life course. Multiple calls made, customer increasingly upset about technical access issues and lack of resolution.', NULL, 'high', NULL, 'PAID', NULL, 'Mandy', 'Kelli Kirk', 'inbound_call', 'CALL 1: Kayla Rivera contacted about not receiving login credentials after enrolling in 2-15 program and paying in full. Agent Mandy escalated to technical support team to prioritize sending credentials within the hour. CALL 2: Customer called back upset - still no login credentials received. Mandy escalated to both technical support AND school director Jason Perez. Customer promised callback within 30 minutes from 407-332-6645 with prior text notification. Issue marked for urgent resolution.', NULL, 'conv_2201k5a45xmdeqda58mzv4ftywhb, conv_6701k5c5rd10ee6tzjw3npebvcjw', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (39, 'Janet', 'Muchmore', '+17275345982', 'jeanette.missing@placeholder.com', '4-40', 'voice_agent', 'renewal_reinstatement', '2025-09-17 15:57:27.531046', '2025-09-17 15:57:27.531046', 'Expired 4-40 insurance license requiring renewal - deadline already passed (February 13th). Requires full 24 hours of CEUs for reinstatement. Multiple calls made for same issue with ongoing urgency.', NULL, 'high', NULL, 'NOT_PAID', NULL, NULL, 'Kelli Kirk', 'Inbound Call - Renewal', 'ORIGINAL CALLS: Jeanette/Janet Muchmore called multiple times about expired license renewal. Agent confirmed deadline was February 13th (already past) and that she needs full 24 hours of CEUs. Customer prefers phone contact and morning calls. Kelli Kirk to call within 1-2 days to coordinate license reinstatement and CEUs. ENHANCED DETAILS: Customer specifically confirmed 4-40 license type, renewal vs reinstatement needed due to expired status past deadline, prefers phone contact over other methods.', NULL, 'conv_7801k5c0s4daf1wbwmchhmqte72j, conv_7801k59pk2dwfgqbsmq1x6aky7pg', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (44, 'Jill', 'Chisholm', '+15616034003', 'jill.thisholm3@gmail.com', 'FL License Support', 'voice_agent', 'new', '2025-10-16 20:43:42.43052', '2025-10-16 20:43:42.43052', 'Needs copy of Florida insurance license, unclear on proper process through Florida DFS', NULL, NULL, NULL, 'NOT_PAID', NULL, NULL, 'Kelli Kirk', 'inbound_call', 'Customer contacted school requesting copy of FL insurance license. Agent clarified school does not handle license copies and directed to FL Department of Financial Services. Customer requested assistance with process. Contact info collected for school follow-up with guidance on obtaining license copy from DFS.', NULL, 'conv_2501k7f3rexwekf94bk2vw2q1zda', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (46, 'Pablo', 'Unknown', '+19547449844', 'pablo.unknown.9547449844@placeholder.com', '215, 220 CE', 'voice_agent', 'new', '2025-10-16 20:45:23.874723', '2025-10-16 20:45:23.874723', 'Needs 20 hours CE total (4 hours updates, 16 hours electives) with deadline of October 31, 2025', NULL, 'moderate', 'self-paced courses', 'NOT_PAID', NULL, 'Sarah Patterson', 'Kelli Kirk', 'inbound_call', 'Pablo called for continuing education information. Holds licenses 215 and 220. Requires 20 CE hours total - 4 hours updates and 16 hours electives - due October 31, 2025. Prefers self-paced course format. Agent Sarah Patterson collected requirements and will pass profile to supervisor Kelli Kirk who will contact within 1-2 days with customized education plan and enrollment details.', NULL, 'conv_0001k6x5r44pec7smkmgz5gvpe6n', 0, NULL);
INSERT INTO public.leads (id, first_name, last_name, phone, email, license_goal, source, status, created_at, updated_at, pain_points, employment_status, urgency_level, payment_preference, payment_status, confirmation_number, agent_name, supervisor, lead_source, call_summary, call_date, conversation_id, unanswered_call_attempts, last_call_attempt_at) VALUES (47, 'Unknown', 'Caller', '+17275059320', 'unknown.caller.7275059320@placeholder.com', 'Continuing Education (Kelly/Kelli)', 'voice_agent', 'new', '2025-10-16 20:46:29.952527', '2025-10-16 20:46:29.952527', 'Extreme frustration with automated system - repeatedly transferred in circles, unable to reach live person despite multiple requests. Specifically requested Kelly for continued education but agent kept looping back to automated menu. Customer explicitly stated dissatisfaction with service quality and demanded ANY live representative.', NULL, 'high', NULL, 'NOT_PAID', NULL, NULL, 'Kelli Kirk', 'inbound_call', 'Caller attempted to reach Kelly/Kelli for continuing education assistance. Agent failed to connect caller to live person, repeatedly transferring back to automated system despite caller''s escalating frustration and explicit demands for human assistance. Call represents critical service failure - caller expressed extreme dissatisfaction with automated system. URGENT: Requires immediate human follow-up and service recovery.', NULL, 'conv_7101k6nwdmxyfv79fspgqezfxkvn', 0, NULL);


--
-- Name: leads_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.leads_id_seq', 47, true);


--
-- Name: leads leads_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.leads
    ADD CONSTRAINT leads_pkey PRIMARY KEY (id);


--
-- Name: created_at_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX created_at_idx ON public.leads USING btree (created_at);


--
-- Name: phone_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX phone_idx ON public.leads USING btree (phone);


--
-- Name: status_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX status_idx ON public.leads USING btree (status);


--
-- PostgreSQL database dump complete
--

